build-deps:
	cargo build --target wasm32-unknown-unknown --release \
	  --manifest-path ../../Cargo.toml \
	  -p liquidity-pool-contract
	cargo build --target wasm32-unknown-unknown --release \
	  --manifest-path ../../Cargo.toml \
	  -p vendor-registry-contract
